let p = document.querySelector('.prompt');

let prompts = ["Do you think you’ve failed yourself in one way or another?",
    "How can you begin to forgive yourself?",
    "What secrets are you holding onto and what harm are they causing?",
    "Are you willing to uncover the sources of your pain? Why or why not?",
    "Do you examine mistakes that you’ve made from a place of compassion or judgment?",
    "What do you need to forgive your younger self for not knowing?",
    "What do you need to know how to do, or learn more about? How is not knowing/learning holding you back?",
    "What anger or frustrations are you holding onto and why?Who do you need to forgive and why?",
    "What experiences have you had with others that you believe you’re still suffering from?",
    "Who have you hurt and why?",
    "How can you mend the harm that you’ve caused others to experience?",
    "Are you upset with God about something that has taken place in your life? Why?",
    "Who do you want to help you in your life? What’s stopping you from cultivating this relationship?",
    "What are some things that you like about yourself that others seem to criticize you about?",
    "What situations are taking place in your community, country or the world that leave you hurting or confused?",
    "How can you contribute to the healing and suffering you see in a positive manner?",
    "What do you need to let go of that you have no control over?",
    "What fears arise from external conditions that are out of your control?",
    "Which external circumstances cause you to experience the most stress?",
    "How can you use your hurt and pain to change situations and/or help someone else?",
    "When do you feel the world stop?",
    "What is your personal motto?",
    "What is the greatest gift you ever received?",
    "Are you an impulsive person or someone who prefers to “wait and see”?",
    "Write about a leader who inspires you.",
    "What irrationally annoys you more than anything else?",
    "What small thing can always bring you a bit of joy?",
    "What is your favorite thing to do on a lazy day?",
    "How often do you take risks?",
    "Write about your happiest memory.",
    "What is your favorite thing about being male or female?",
    "Who is your favorite president? What do you admire about him?",
    "How long do you think it will be before we see a female president?",
    "Do you think it’s important to be a part of a community? Why or why not?",
    "Write a thank-you note to someone who has made a difference in your life.",
    "What piece of modern technology are you most grateful to have?",
    "What would your life today be like without the Internet?",
    "Do you feel anonymous online? Why or why not?",
    "Do you prefer to binge-watch TV or keep up week-to-week? Why or why not?",
    "Write about your writing habits and what they say about you.",
    "What is something you’ve always wanted to try but have never gotten around to?",
    "Can money buy happiness?",
    "Write about a time when you had a profound disagreement with a friend.",
    "If you could have a book with all the answers, would you read it? Why or why not?",
    "What goal are you working on right now?",
    "When do you feel most connected to other people?",
    "What is the greatest challenge you’ve ever faced?",
    "Write about a time when you couldn’t stop laughing.",
    "What is the most intense dream you’ve ever had?",
    "What is your favorite way to treat yourself after a long week?",
    "What thought scares you more than anything else? How do you cope with it?",
    "What are you exceptional at? Describe your talent.",
    "When do you feel most at peace?",
    "If you could create your own day of awareness, what would it be for?",
    "What was the most exciting piece of news you ever received?",
    "Who knows you better than anyone else?",
    "How do you define success? Who is a successful person according to your definition?",
    "Are you the life of the party or someone who prefers to sit back and observe?",
    "Write about the last time you helped someone.",
    "What is the most interesting fact you know—and why does it interest you?",
    "Write about a time when you heard, read, or saw something that you weren’t supposed to. What happened?",
    "Have you ever fallen in love?",
    "Do you follow current events? Why or why not?",
    "What is the greatest benefit of journaling?",
    "If you could have any one question answered, what would it be? How would the answer impact your life?",
    "What is the earliest lesson you remember learning from your parents?",
    "Write about one thing from your childhood that you will always carry with you.",
    "How do you define “family”?",
    "Do you believe in ghosts or spirits? Why or why not?",
    "How frequently do you exercise or engage in physical activity? Are you satisfied with your habits? Why or why not?",
    "Write about an aspect of another culture that interests you and that you’d like to learn more about.",
    "Write about something you love that you think everyone else should try, too.",
    "Would you ever consider going to space? Why or why not?",
    "What is the most important thing you look for in a friend?",
    "What value do you hold most dear? Why?",
    "Choose three words to describe the current state of your life—and then explain why you chose them.",
    "Write about a time when you created something amazing.",
    "Would you rather be rich, successful, healthy, or famous? Why?",
    "What do you think one of the hardest jobs in the world is? Would you ever consider doing it?",
    "Write about a time when someone confided in you. How did their trust make you feel?",
    "Write about a time when you encountered a bully—and what you did to address the situation.",
    "Are you more scientific-minded or creative-minded? How does that affect your life?",
    "Write about a special memory that might not have looked so special to someone on the outside.",
    "What kind of impact do commercials and advertising have on your life?",
    "What do you spend most of your time doing? How do you feel about that?",
    "Write a 50-word description of yourself that you could give to someone you’d never met. How accurately does it describe you?",
    "What was the most peaceful moment during the day?",
    "Describe something you learned today that you didn’t know before.",
    "Would you change any of the decisions you made today?",
    "How were your meals today? Do you feel nourished?",
    "What frightened you today?",
    "Who do you wish you had talked to today? How do they improve your life?",
    "Describe the moments of frustration you felt today. How would your day have changed if those moments were different?",
    "If you’d had another hour during the day, how would you have spent it?",
    "Did something (or someone) empower you today?",
    "Did you stop yourself from doing something you enjoy today? Why or why not?",
    "Reflect on how your body feels. Where are you storing your stress? What put it there?",
    "Who helped you the most today? Who did you help the most?",
    "Describe your day from another person’s perspective. Is it different from yours?",
    "If you were in charge, what would you forbid immediately?",
    "What needs to change in your job for you to feel fulfilled?",
    "Write about a hobby that you’d like to pick up.",
    "If you could relive any day of your life and change nothing, what day would you choose?",
    "How would you like your life to be different in a year? How would you like it to be the same?",
    "If you had to live in another country, where would you live?",
    "How could you change your life to become a hero to someone else?",
    "What was something you desperately wanted as a child? What do you desperately want now?",
    "If you could take any college course you wanted, what would you take?",
    "Describe your ideal weekend. What would it include? What wouldn’t it include?",
    "Rewrite a conversation you’ve had in the way you wish it had gone.",
    "What would you do if you needed to change your career or major?",
    "Write a note to a teacher who inspired you. How have you used their lessons in your current life?",
    "What would you say to a childhood bully if you could?",
    "Write a letter to your teenage self.",
    "Put yourself 20 years in the future. Write a letter to your future self with questions and predictions.",
    "Write a thank you letter to someone after they gave you a terrible gift.",
    "Craft a breakup letter to a bad habit.",
    "Think about your first crush or love. Write them the letter you wish you’d sent.",
    "Write a letter from someone else to you. What do you need to hear from them?",
    "Look at your last few text messages. Rewrite one of them into a longer letter as if you were in the eighteenth century.",
    "Write a letter to someone you’ve lost.",
    "What was your best age so far?",
    "Do you have a memory that should be happy, but instead makes you sad? What about the other way around?",
    "When is a time in your life that you felt successful?",
    "Think about your best friend in childhood. What did you like to do together?",
    "Write about a trip you took where something (or everything!) didn’t go according to plan.",
    "Think about a lesson your parents taught you either by doing something well or not doing it well.",
    "When in your life have you felt brave?",
    "What book made you fall in love with reading?",
    "How old were you when you first felt like an adult?",
    "What brings you joy?",
    "Describe a place where you felt happiest.",
    "What was your greatest fear, and how did you conquer it?",
    "Write a letter to someone that you always want to thank but have never had the chance to do so.",
    "What is something that you would like to change about yourself? How can you change it?",
    "Write a letter to someone that you care about to tell them how you feel.",
    "Reflect and write letters to yourself with constructive feedback to improve yourself.",
    "Write about the people around you to describe what they are like, and what are your views about their actions etc.",
    "List down a bucket list with the things that you have always wanted to do.",
    "Where do you see yourself in the next 1, 3, 5, 10 years from now?",
    "What is something that you would like to achieve? How do you plan on reaching your goal(s)?",
    "Write about a song and a feeling it invoked in you. ",
    "Recall an important memory from your childhood and tell it from the perspective of someone else who was present.",
    "Write about an item you have that isn’t expensive but means a lot to you.",
    "What color do you feel like today and why?",
    "Describe your favorite room in your home or apartment.",
    "If you could live inside one of your favorite stories, what would you change about it?",
    "Write about why you want to write. ",
    "Write about something nice a stranger did for you.",
    "What was the last piece of media you read, heard, or saw that inspired you? ",
    "What is a dream you’ve had that you want to live in forever?",
    "Write about what you think the world will look like in 10 years.",
    "Write about a time you witnessed community solidarity.",
    "What are five things you appreciate about yourself?",
    "What are three great things that happened yesterday?",
    "What are 30 things that bring you joy?",
    "What are you looking forward to right now? If you can’t think of anything, what can you do to change that?",
    "What is one thing under $100 that has made your life easier?",
    "What are 10 things you’re actively enjoying about life right now?",
    "Write about the most fun you had recently. What were you doing and who with?",
    "Name the top three emotions you are feeling at the moment. What are the emotions you want to feel today?",
    "What is the one thing you would tell your teenage self if you could?",
    "What is your body craving at the moment?",
    "What are 10 questions you wish you had the answers to right now?",
    "What do you know to be true today that you didn’t know a year ago?",
    "What are you scared of right now?",
    "What’s not working in your life right now?",
    "Write someone a letter with whom you have an unresolved issue.",
    "Write about someone you miss, what do you miss about them? How do they make you feel?",
    "What would your ideal day look like? Where would you be, what would you be doing and who with?",
    "Describe your perfect home – where is it, what does it look like and who do you share it with?",
    "When you were younger, what did you want to be when you grew up and why?",
    "What do you need more of in your life?",
    "If failure wasn’t possible, what would you be doing right now?",
    "If you only had one year left of life, what would you do?",
    "In another life, who would you want to be? Write out this character, what they do for a living, their personality traits, etc.",
    "What’s something you wish others knew about you?",
    "Who is someone you admire? What qualities do you love about them?",
    "Who is someone you envy and why?",
    "What distracts you from what’s truly important each day?",
    "If you decided right now that you had enough money, and that you would always have enough, what would you do with your life?",
    "How do you want to contribute your talents and passions to the world? Who could be touched by you and how would it affect them?",
    "Is there someone that you have not fully forgiven? How might you fully forgive them?",
    "What was the hardest thing you've gone through in your life and how did you get through it?",
    "What experience made you feel sad in the past? What meaning can you make from this experience?",
    "What makes you feel angry? How can you use this anger to make a positive impact in your life or the world?",
    "What makes you feel anxious? How might you talk back to these anxious thoughts in ways that help you feel calmer?",
    "Is there someone you never properly thanked? How might you express your gratitude?",
    "What are all the things you're grateful for today?",
    "What was something positive you experienced recently? Elaborate.",
    "What is your favorite activity? Elaborate.",
    "What are some things that give your life meaning?",
    "What are three good things about today?",
    "What are your positive personality traits?",
    "Who would you like to have a stronger relationship with and what might you do to grow that relationship?",
    "What are some random acts of kindness that you could do in the next year?",
    "How do you manage your emotions, and how might you manage them more effectively?",
    "What are the beliefs or principles that you live your life by?",
    "What are your values and why are they important to you?",
    "What are your strengths and weaknesses?",
    "Who are you at the core?",
    "How do you relate to others? How might you relate to others in ways that better serve you and them?",
    "How healthy are you and how could you be healthier?",
    "If you have an illness, how do you feel about that illness? ",
    "In what ways does your health impact your life?",
    "How can your health issues teach you something new or build character?",
    "What are your short-term and long-term goals?",
    "What would you like to have accomplished by the end of your life?",
    "What are the things you could do today to start moving towards your goals?",
    "What big dreams do you want to manifest?",
    "I am an awesome person because...",
    "When I feel angry, I tend to...",
    "When I feel sad, I tend to...",
    "I would describe my relationships with other people as being...",
    "A recent challenge I had was...",
    "When I am struggling, I tend to work through the difficulty by...",
    "My favorite things to do to calm myself are...",
    "If I'm having a rough day, some healthy things I can do to feel better are...",
    "I want to forgive...",
    "I feel ashamed when...",
    "I tend to eat more junk food when I'm feeling...",
    "The foods that make me feel the most energized and happy are...",
    "After exercising I feel...",
    "When I get a good night's sleep I feel...",
    "List all the emotions you've felt in your life.",
    "List all the things you can do to improve your emotions.",
    "Explain how your emotions change over time.",
    "Define emotional support.",
    "Describe what it feels like to be overwhelmed.",
    "Describe how it feels to be rejected.",
    "Explain the difference between feeling calm and feeling anxious.",
    "Are you a reliable person? Why and why not? (Explore both sides)",
    "What do you love and hate about yourself? Why?",
    "What makes you you?",
    "What do you want in life?",
    "What does it mean to you to have well-being?",
    "List some examples of when you have been vulnerable in the past. When are some times you could be more vulnerable in the future?",
    "What are the good habits you would like to build in the next 5 years?",
    "How do you build rapport with another person?",
    "What scares you?",
    "Do you have a plan? Do you need a plan? Have you had a plan fall spectacularly to pieces?",
    "What is your take on soul mates?",
    "Are you a worrier? Is there a particular worry that you can’t shake? How do you cope with worry?",
    "Dear Past Me . . .",
    "Dear Future Me . . .",
    "Places you’ve enjoyed visiting.",
    "Things you’ve done that you previously thought you could never do.",
    "The people you most admire.",
    "Your favorite books.",
    "Your favorite movies.",
    "Your favorite songs.",
    "Your top five short term goals.",
    "Your top five long term goals.",
    "Nobody knows that I . . .",
    "Dear ____, it weighs on me that I never told you . . .",
    "The biggest lie I’ve ever told is . . .",
    "Is there anything you feel guilty about?  Is there anything you need to be forgiven for?",
    "What’s the worst thing you’ve ever done?",
    "What’s your secret desire?",
    "What’s the most outrageous thing you’ve ever done?",
    "The most terrifying moment of my life was . . .",
    "The most fun I’ve ever had . . .",
    "The most surprised I’ve ever been . . .",
    "The most disappointed I’ve ever been . . .",
    "What are you looking forward to the most?",
    "Three things you can’t go without.",
    "Three favorite book characters.",
    "Three things you want in a relationship.",
    "If you had to evacuate your home because of a natural disaster, what three things would you take with you?",
    "Three things you’d do if you weren’t so afraid.",
    "Three favorite TV shows.",
    "My saddest memory is  . . .",
    "Some of the things that make me happy are . . .",
    "How do you deal with anger?",
    "How easy is it for you to forgive those who have caused you pain?",
    "What is the dominant emotion in your life right now?",
    "My favorite Sunday ritual . . .",
    "The Holiday traditions I most look forward to . . .",
    "Things I always did with my dad when I was small . . .",
    "Things I always did with my mom when I was little . . .",
    "If you could have dinner with anyone currently alive, who would it be?",
    "If you could meet any fictional character, who would it be?",
    "If you could change one thing about your present life, what would it be?",
    "If you could live anywhere you wanted, where would you live?",
    "If you could go back in time and change one things from your past, what would it be?",
    "What was your favorite toy?",
    "Did you ever get lost?",
    "Who was your best friend in elementary school?",
    "Did you ever run away from home?",
    "As a child, what did you want to be when you grew up?",
    "What was your favorite subject in school?",
    "Who was your favorite teacher?",
    "What’s your first memory?",
    "What was your favorite cartoon?",
    "What book did you read over and over again as a child?",
    "What is your most vivid memory of the kitchen in your childhood?",
    "As a child, who was your favorite relative?",
    "Who made you feel good this week?",
    "What was the biggest mistake you made this week?",
    "What did you do this week that moved you closer to reaching your goals?",
    "Is there anything you did this week that you wish you’d done differently?",
    "What did you most enjoy doing this week?",
    "How did you procrastinate on important tasks this week?",
    "What did you learn this week?",
    "What’s the funniest thing that happened to you this week?",
    "Write a letter to someone you need to forgive.",
    "Write a letter to someone who believed in you even when you didn’t believe in yourself.",
    "Write a letter to be read by each of your loved ones after you’ve passed away.",
    "Write a fan letter to your favorite actor/actress.",
    "Write a letter to the editor of your favorite magazine telling them what features you would like to see included in the magazine.",
    "Is there something you’re reluctant to tell someone?  Write a letter to help y0u organize your thoughts.",
    "Write about your first dance.",
    "Write about your first crush.",
    "Write about your first week in college.",
    "Write about your first job.",
    "Write about the first apartment you ever rented.",
    "When did you feel truly independent for the first time?",
    "What would you do if you knew you could not fail?",
    "What would you do if money were no object?",
    "What would you ask for if a genie granted you three wishes?",
    "What’s your wildest dream?",
    "What would you do if you could live a day without consequences?",
    "What grand adventure do you wish you could go on?",
    "If you could become an expert in any subject or activity, what would it be?",
    "What would your perfect day be like?",
    "Close your eyes and imagine the kind of world you would like to see.  What is it like?",
    "What makes you unique?",
    "How do you stand out from the crowd?",
    "What are your best character traits?",
    "What are you really good at?",
    "How would you describe yourself?",
    "How would your best friend describe you?",
    "What character traits do you need to work on?",
    "What are some of your idiosyncrasies?",
    "How do you indulge yourself?  Do you need to indulge yourself more often?",
    "How do you think others see you when they meet you for the first time?",
    "How would you like to make this world a better place? How can you best share your gifts with the world?",
    "What qualities do you want in a romantic partner? What are the top ten characteristics that you look for in a romantic partner?",
    "What are the top ten qualities a friend should have (treats people with respect; listens but doesn’t judge; has a quirky sense of humor; is an artist; lives with passion; doesn’t sweat the small stuff; is loyal and trustworthy)?",
    "What would make you feel spiritually fulfilled?",
    "What famous world festivals would you like to attend?",
    "Was there anything noteworthy about your mother’s upbringing –she grew up in extreme poverty or extreme wealth; she grew up during the Great Depression; she grew up surrounded by artists, philosophers, or politicians; her family moved around a lot when she was growing up; and so on?",
    "Write down three of your father’s favorites (it could be his favorite singer, his favorite book or author, his favorite movie, his favorite time of the year, his favorite basketball player, his favorite artist, his favorite meal, his favorite dessert, and so on).",
    "Do you have any famous or high profile family members? If so, write about them.",
    "Are you satisfied with your life right now?",
    "What would you like to change about your life?",
    "What is the best thing about your life?",
    "What is your biggest regret?",
    "What are you most grateful for in your life?",
    "What is your best childhood memory?",
    "What do you remember the most when you think of home?",
    "What is the best thing about growing up?",
    "When people think of you, how would they describe you?",
    "If there is anything you can do right now, what would you do?",
    "If money was not a problem, how would live your life?",
    "Is there anything you imagine a lot as a child?",
    "What do you always wish for?",
    "What are your goals for next year?",
    "What has the pandemic thought you?",
    "Are friends more important or family?",
    "If you could turn back time, to which moment would you like to go back too?",
    "If you had $5000 to spend on yourself, how would you spend it?",
    "If you could be anything you want to be without being judged, who would you be?",
    "Is there anything you wished you had learned when you were younger?",
    "What advice would you give to your younger self?",
    "Is there a new skill you would like to learn?",
    "What is your goal?",
    "Is there any book that you would also re-read?",
    "What is the best advice you have ever received?",
    "What is the first thing you notice when you meet someone new?",
    "What are you most thankful for in your life?",
    "What is the one thing you wish you can do at some point in your life?",
    "Create a bucket list of things you would like to achieve before the age of 50.",
    "Write a letter to yourself that you would open 5 years from now.",
    "What scares yours about dying?",
    "Do you think you are often misunderstood?",
    "If you can change one thing about the world, what would you change?",
    "Who is the biggest influencer in your life?",
    "Who do you admire the most in your life?",
    "Did you expect your life would be the way it is right now?",
    "“If I had the courage, I would…..”",
    "Do you think God really exist?",
    "Look at the room you sitting at right now, how does it make you feel?",
    "don’t forget to check this out",
    "What is your biggest achievement so far?",
    "Do you think your life is going according to plan?",
    "What are you thinking about in this exact moment?",
    "Is there anything that is stopping you from achieving your dreams?",
    "What keeps you up at night?",
    "What is the one thing you wish people know about you?",
    "What are your stress triggers?",
    "What makes you angry?",
    "What motivates you?",
    "What are the things that push you down?",
    "What do you do to relax?",
    "On a scale from 1 to 10 how healthy is your lifestyle?",
    "Is there any unhealthy habits you would like to give up?",
    "What do you do to nurture your soul?",
    "What can I do to feel happier?",
    "What are the negative energy I should remove in my life?",
    "What is my biggest struggle?",
    "What negative thoughts do I need to stop saying to myself?",
    "What morning affirmations should I say to myself so I feel good every day?",
    "What should I do during the weekend so I can feel recharged for Monday?",
    "What new skill should I learn or acquire?",
    "What is stopping me from going after my dreams?",
    "What are the 3 words that describe me the most?",
    "Is there anything kind that I did recently?",
    "How can I support a local charity besides donating money?",
    "Is having more money going to make me happier?",
    "What does an ideal day look like?",
    "What are my top 3 goals for the rest of the year?",
    "How do I describe the friendship I have with my friends?",
    "How can I be kinder to myself?",
    "Am I being to hard on myself?",
    "What would I do if I knew I would never fail?",
    "Write your eulogy",
    "What’s the highlight of your day so far?",
    "Imagine aliens landed on earth, what will they say to humans?",
    "Finish this sentence, the smell of an apple reminds me of….”",
    "You get 3 wishes fulfilled, what are your wishes?",
    "Write safety instructions for passengers traveling to the moon.",
    "Summarise your life story in less than 500 words",
    "You woke up one day and found yourself in the opposite sex, what happens next?",
    "You have been voted as the leader of your country, what is the first thing you would do?",
    "Pick a country you have never visited, why would you move there?",
    "What advice do you often give people but never follow it yourself?",
    "our favorite movie this month",
    "The best place you visited this month",
    "The best day of the month",
    "Something you let go of this month",
    "Something new you learn this month",
    "What are the things you look forward to next month?",
    "Some of the worst/best jokes you heard this month?",
    "What is your favourite music this month?",
    "The biggest news headline that happened this month,",
    "What are the goals accomplished this month?",
    "Did you fail at something this month?",
    "What held you back this month?",
    "Who helped you the most?",
    "7 random things you did this month.",
    "What are you most grateful for?",
    "Who is the last person you said sorry to this month?",
    "What is the best part of your month?",
    "What is your favourite thing about the month?",
    "Name 3 new things you tried this month?",
    "How did you relax?",
    "What motivated you?",
    "What is the one goal you achieved this month?",
    "What are you most proud of?",
    "What are the things you look forward to next month?",
    "What is the best thing that happened to you recently?",
    "Who/who made you feel special and loved?",
    "What is your favorite outdoor activity?",
    "Name 3 people you can rely on",
    "Name someone that was kind to you today",
    "Who are the people that will always make you smile?",
    "What do you like most about your current life and situation?",
    "Who do you do to unwind?",
    "Name 2 people you are grateful for in your life?",
    "What do you enjoy doing the most?",
    "Write things you like most about your family",
    "What are things you take granted for in your life?",
    "Name the people that would cheer you up when you are feeling down?",
    "What inspire you the most?",
    "What do you look forward to in your life?",
    "Write about something magical that happened to you recently",
    "Write about the best food you recently ate.",
    "Write about a book you enjoy reading.",
    "Write about something that keeps you nice and warm",
    "Write about a wish that came true",
    "Write about a teacher you are grateful for.",
    "Look around the room you are in right now, and write all the beautiful things you can see in it.",
    "What skills are you grateful for in your life?",
    "What do you think gratitude means?",
    "What are the things about this year you are thankful for?",
    "What are the two thing in your life you are thankful for?",
    "How do you practice gratitude on a daily basis?",
    "Write down new habits you would like to implement.",
    "When you look into the mirror, what do you see?",
    "Write about the moment you overcome something difficult by believing in yourself.",
    "Write down the emotions you are feeling right now as you are writing this.",
    "Review your goals in the last 1 year and see how far you have made it.",
    "Describe the happiest place on earth.",
    "Top 3 goals for the year",
    "Long term goals",
    "Skills you would like to learn this year…",
    "New hobbies you would like to try…",
    "3 ways you will make this year a good one….",
    "Ways in which you are amazing……",
    "Gifts you would like to receive from others….",
    "100 things you are grateful for…..",
    "Money-making ideas you would like to try…",
    "Things you would like to do with the family……",
    "Things you love about your close friends…",
    "Self-care practices you would like to try….",
    "New restaurants you would like to visit…",
    "Summer activities you would like to do this year…",
    "New Christmas celebration this year…..",
    "Movies you would like to watch….",
    "People you would like to thank….",
    "Adventures you want to try…..",
    "Experiences you would like to cherish…..",
    "Describe a time in your life where God has rescued you. Do you believe He’ll do it again?",
    "Write a scripture that brings you peace. What is God saying to you?",
    "Describe a time where you believed God spoke to you.",
    "Write a prayer of surrender to God.",
    "How can you be bold and courageous for the Lord.",
    "Be still. What is God telling you now?",
    "How can you serve God better?",
    "How can you be a light to others in a dark world?",
    "Describe a time when God used a bad situation for your good.",
    "What do you feel God is asking you to change?",
    "What do you imagine heaven will be like?",
    "When do you feel most distant from God?",
    "How are you hurting others with your pride?",
    "Ecclesiastes tells us there is a season for everything. What season are you in right now?",
    "Write out the lyrics of a Christian song or hymn that brings you joy.",
    "Write a scripture that brings you joy. How can you apply it to your life?",
    "Describe a blessing that happened this week.",
    "Write a Psalm of worship to God.",
    "Do you find it hard to apologize? If so, why?",
    "The bible specifically speaks of joy, not happiness. In what way are they different?",
    "Are you self-righteous about something? What can you do about it?",
    "What are the character attributes you think a Christian should have?",
    "When you get offended by something how does your pride react?",
    "Pick a bible character. What can we learn from his/her life?",
    "What do you need to confess to God?",
    "Write a letter of forgiveness to an enemy.",
    "Is there something that you haven’t forgiven yourself for? How can you receive the healing of the Lord?",
    "Write 5 scripture verses that make you feel strong and courageous.",
    "What does forgiveness look like?",
    "If you are struggling though something, what do you think God wants to you to learn?",
    "List all the needs God is currently meeting.",
    "What do you love most about your church family?",
    "What does God say about pride (see the scriptures)?",
    "Describe someone in your life who exemplifies humility.",
    "What are your God-given gifts and talents? How can you use them to advance the Kingdom?"
];


function generate(){
    let num = Math.floor(Math.random()*543);
    p.innerHTML = `${prompts[num]}`;
    p.style.display = 'block';
}
